"""Provider-independent generative intelligence boundary for IRIS."""

from iris.intelligence.contracts import IntelligenceProvider
from iris.intelligence.models import (
    IntelligenceRequest,
    IntelligenceResult,
    IntelligenceStatus,
    ModelCapability,
    ModelDescriptor,
    ModelLocation,
)
from iris.intelligence.registry import (
    DuplicateProviderError,
    ProviderNotFoundError,
    ProviderRegistry,
)
from iris.intelligence.routing import (
    CandidateRejection,
    CandidateRejectionReason,
    CandidateResolution,
    CandidateResolver,
    DeterministicRoutingPolicy,
    DuplicateIntelligenceResourceError,
    EmptyCandidateSetError,
    IntelligenceNeed,
    IntelligencePreferences,
    IntelligenceRequirements,
    IntelligenceResource,
    IntelligenceRoute,
    IntelligenceRouter,
    IntelligenceRouteReason,
    IntelligenceRouteStatus,
    ModelAffinity,
    RoutingPolicy,
    RoutingPolicyContractError,
)
from iris.intelligence.runtime import (
    IntelligenceRuntime,
    ModelNotFoundError,
    ModelUnavailableError,
    ProviderContractError,
)

__all__ = [
    "CandidateRejection",
    "CandidateRejectionReason",
    "CandidateResolution",
    "CandidateResolver",
    "DeterministicRoutingPolicy",
    "DuplicateProviderError",
    "DuplicateIntelligenceResourceError",
    "EmptyCandidateSetError",
    "IntelligenceNeed",
    "IntelligencePreferences",
    "IntelligenceProvider",
    "IntelligenceRequest",
    "IntelligenceRequirements",
    "IntelligenceResource",
    "IntelligenceResult",
    "IntelligenceRoute",
    "IntelligenceRouteReason",
    "IntelligenceRouteStatus",
    "IntelligenceRouter",
    "IntelligenceRuntime",
    "IntelligenceStatus",
    "ModelCapability",
    "ModelDescriptor",
    "ModelAffinity",
    "ModelLocation",
    "ModelNotFoundError",
    "ModelUnavailableError",
    "ProviderContractError",
    "ProviderNotFoundError",
    "ProviderRegistry",
    "RoutingPolicy",
    "RoutingPolicyContractError",
]
